### ISSUE TITLE
Add visual monitor

### ISSUE THREAD

**Issue by amitaibu** [Gizra/clalbit-shoov#1]
https://www.clalbit.co.il/Pages/default.aspx

**Comment by mldk-tech** [comment]
https://app.shoov.io/#/screenshots/17978

**Comment by mldk-tech** [comment]
http://gfycat.com/SafeMagnificentIlsamochadegu

**Comment by mldk-tech** [comment]
![ct8uyopu8ae01rt](https://cloud.githubusercontent.com/assets/5812423/12536714/b8f99e68-c2b5-11e5-978e-968251842dcc.jpg)

**Comment by amitaibu** [comment]
I've changed the repo name on shoov, can you try again please

**Comment by mldk-tech** [comment]
Done
https://app.shoov.io/#/screenshots/22019

**Comment by amitaibu** [comment]
gif as-well

**Comment by mldk-tech** [comment]
:+1: Update
http://gfycat.com/GleamingCompassionateArabianhorse
